/**
 * Export design tokens to Python constants format
 * Generates a constants.py file compatible with givecalc and other Python tools
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { colors, TEAL_PRIMARY, TEAL_ACCENT } from '../dist/tokens/colors.js';
import { typography } from '../dist/tokens/typography.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const outputDir = path.join(__dirname, '..', 'dist', 'python');
const outputFile = path.join(outputDir, 'constants.py');

function generatePythonConstants(): string {
  const lines: string[] = [
    '"""',
    'PolicyEngine Design System - Auto-generated Python Constants',
    '',
    'DO NOT EDIT THIS FILE DIRECTLY.',
    'Generated from @policyengine/design-system TypeScript tokens.',
    '',
    'To regenerate: npm run export-python --workspace=@policyengine/design-system',
    '"""',
    '',
    '# Primary brand colors',
    `TEAL_PRIMARY = "${TEAL_PRIMARY}"`,
    `TEAL_ACCENT = "${TEAL_ACCENT}"  # Legacy accent color`,
    '',
    '# Semantic colors',
    `SUCCESS_GREEN = "${colors.success}"`,
    `WARNING_YELLOW = "${colors.warning}"`,
    `ERROR_RED = "${colors.error}"`,
    `INFO_BLUE = "${colors.info}"`,
    '',
    '# Background colors',
    `BACKGROUND_PRIMARY = "${colors.background.primary}"`,
    `BACKGROUND_SIDEBAR = "${colors.background.secondary}"`,
    `BACKGROUND_TERTIARY = "${colors.background.tertiary}"`,
    '',
    '# Text colors',
    `TEXT_PRIMARY = "${colors.text.primary}"`,
    `TEXT_SECONDARY = "${colors.text.secondary}"`,
    `TEXT_TERTIARY = "${colors.text.tertiary}"`,
    '',
    '# Border colors',
    `BORDER_LIGHT = "${colors.border.light}"`,
    `BORDER_MEDIUM = "${colors.border.medium}"`,
    `BORDER_DARK = "${colors.border.dark}"`,
    '',
    '# Gray scale',
    `GRAY_50 = "${colors.gray[50]}"`,
    `GRAY_100 = "${colors.gray[100]}"`,
    `GRAY_200 = "${colors.gray[200]}"`,
    `GRAY_300 = "${colors.gray[300]}"`,
    `GRAY_400 = "${colors.gray[400]}"`,
    `GRAY_500 = "${colors.gray[500]}"`,
    `GRAY_600 = "${colors.gray[600]}"`,
    `GRAY_700 = "${colors.gray[700]}"`,
    `GRAY_800 = "${colors.gray[800]}"`,
    `GRAY_900 = "${colors.gray[900]}"`,
    '',
    '# Primary color scale',
    `PRIMARY_50 = "${colors.primary[50]}"`,
    `PRIMARY_100 = "${colors.primary[100]}"`,
    `PRIMARY_200 = "${colors.primary[200]}"`,
    `PRIMARY_300 = "${colors.primary[300]}"`,
    `PRIMARY_400 = "${colors.primary[400]}"`,
    `PRIMARY_500 = "${colors.primary[500]}"`,
    `PRIMARY_600 = "${colors.primary[600]}"`,
    `PRIMARY_700 = "${colors.primary[700]}"`,
    `PRIMARY_800 = "${colors.primary[800]}"`,
    `PRIMARY_900 = "${colors.primary[900]}"`,
    '',
    '# Font families',
    `FONT_UI = "${typography.fontFamily.primary.split(',')[0]}"`,
    `FONT_CHART = "${typography.fontFamily.chart.split(',')[0]}"`,
    `FONT_MONO = "${typography.fontFamily.mono.split(',')[0]}"`,
    '',
    '# Neutral colors',
    `WHITE = "${colors.white}"`,
    `BLACK = "${colors.black}"`,
    '',
    '',
    '# Color dictionaries for programmatic access',
    'COLORS = {',
    '    "primary": {',
  ];

  // Add primary colors dict
  Object.entries(colors.primary).forEach(([key, value]) => {
    if (key !== 'alpha' && typeof value === 'string') {
      lines.push(`        ${key}: "${value}",`);
    }
  });
  lines.push('    },');

  // Add gray colors dict
  lines.push('    "gray": {');
  Object.entries(colors.gray).forEach(([key, value]) => {
    lines.push(`        ${key}: "${value}",`);
  });
  lines.push('    },');

  // Add semantic colors
  lines.push('    "semantic": {');
  lines.push(`        "success": "${colors.success}",`);
  lines.push(`        "warning": "${colors.warning}",`);
  lines.push(`        "error": "${colors.error}",`);
  lines.push(`        "info": "${colors.info}",`);
  lines.push('    },');

  // Add background colors
  lines.push('    "background": {');
  lines.push(`        "primary": "${colors.background.primary}",`);
  lines.push(`        "secondary": "${colors.background.secondary}",`);
  lines.push(`        "tertiary": "${colors.background.tertiary}",`);
  lines.push('    },');

  // Add text colors
  lines.push('    "text": {');
  lines.push(`        "primary": "${colors.text.primary}",`);
  lines.push(`        "secondary": "${colors.text.secondary}",`);
  lines.push(`        "tertiary": "${colors.text.tertiary}",`);
  lines.push(`        "inverse": "${colors.text.inverse}",`);
  lines.push('    },');

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

// Create output directory if it doesn't exist
fs.mkdirSync(outputDir, { recursive: true });

// Write the Python file
const content = generatePythonConstants();
fs.writeFileSync(outputFile, content);

console.log(`✅ Generated Python constants: ${outputFile}`);
console.log(`   Contains ${content.split('\n').length} lines`);
