/**
 * Test fixtures for MarkdownFormatter component tests
 *
 * Note: Plotly mock must be defined inline in test files due to vi.mock hoisting.
 * Use: vi.mock('react-plotly.js', () => ({ default: vi.fn(() => null) }));
 */

/**
 * Sample markdown content for testing
 */
export const MARKDOWN_SAMPLES = {
  PARAGRAPH: 'Hello world',
  WITH_LINK: 'Visit [Example](https://example.com)',
  WITH_HEADING: '## Section Title',
  WITH_BOLD: 'This is **bold** text',
  WITH_LIST: '- Item 1\n- Item 2',
  EMPTY: '',
} as const;

/**
 * Sample footnotes for FootnotesSection tests
 */
export const FOOTNOTE_SAMPLES = {
  /**
   * Basic footnotes without links
   */
  BASIC: {
    '1': 'First footnote text.',
    '2': 'Second footnote text.',
  } as Record<string, string>,

  /**
   * Empty footnotes object
   */
  EMPTY: {} as Record<string, string>,

  /**
   * Footnote containing a markdown link
   */
  WITH_LINK: {
    '1': 'See [source](https://example.com) for details.',
  } as Record<string, string>,

  /**
   * Footnote with multiple links
   */
  WITH_MULTIPLE_LINKS: {
    '1': 'See [link1](https://one.com) and [link2](https://two.com).',
  } as Record<string, string>,

  /**
   * Footnotes in non-numeric key order (for sorting tests)
   */
  UNORDERED: {
    '3': 'Third.',
    '1': 'First.',
    '2': 'Second.',
  } as Record<string, string>,
} as const;

/**
 * Expected link attributes for testing
 */
export const EXPECTED_LINK_ATTRS = {
  EXTERNAL_TARGET: '_blank',
  EXTERNAL_REL: 'noopener noreferrer',
} as const;

/**
 * Expected footnote IDs generated by FootnotesSection
 */
export const FOOTNOTE_IDS = {
  FN_1: 'user-content-fn-1',
  FN_2: 'user-content-fn-2',
  FNREF_1: 'user-content-fnref-1',
  FNREF_2: 'user-content-fnref-2',
} as const;

/**
 * Expected href patterns for footnote links
 */
export const FOOTNOTE_HREFS = {
  BACK_REF_1: '#user-content-fnref-1',
  BACK_REF_2: '#user-content-fnref-2',
} as const;
