name: Chromatic

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  chromatic:
    name: Visual regression tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for TurboSnap to diff changes
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build design system
        run: bun run design-system:build

      - name: Run Chromatic
        working-directory: ./app
        run: >-
          bunx chromatic
          --only-changed
          --build-script-name="storybook:build"
          --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          ${{ github.event_name == 'push' && '--auto-accept-changes' || '' }}
          ${{ github.event_name == 'pull_request' && format('--patch-build={0}...main', github.head_ref) || '' }}
        env:
          VITE_APP_MODE: website
