name: Deploy to App Engine

on:
  push:
    branches: 
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests (includes type checking)
      run: npm test
    
    - name: Build application with Vite
      run: .github/scripts/build-with-vite.sh
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/83599293185/locations/global/workloadIdentityPools/prod-github-provider/providers/prod-github-provider"
        service_account: "workflow-identity-provider@policyengine-app-v2.iam.gserviceaccount.com"
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: policyengine-app-v2
    
    - name: Deploy to App Engine
      run: gcloud app deploy --quiet --project policyengine-app-v2